---
#station_date:出发日期，格式ex：2018-01-06
#station_trains:过滤车次，格式ex：
                #    - "G1353"
                #    - "G1329"
                #    - "G1355"
                #    - "G1303"
                #    - "G1357"
                #    - "G1305"
                #    - "G1359"
                #    - "G1361"
                #    - "G1373"
                #    - "G1363"
#from_station: 始发站
#to_station: 到达站
#set_type: 坐席(商务座,二等座,特等座,软卧,硬卧,硬座,无座)
#is_more_ticket:余票不足是否自动提交
#select_refresh_interval:抢票刷新间隔时间，1为一秒，0.1为100毫秒，以此类推
#expect_refresh_interval:售票未开始，等待刷新间隔时间，1为一秒，0.1为100毫秒，以此类推
#ticket_black_list:加入小黑屋的等待时间，默认3 min
#ticke_peoples: 乘客
#damatu：打码兔账号，用于自动登录

set:
  station_date:
    - "2018-02-03"
    - "2018-02-04"
    - "2018-02-05"
    - "2018-02-06"
    - "2018-02-07"
    - "2018-02-08"

  station_trains:
    - "K770"
    - "G1006"
    - "G1110"
    - "G68"
    - "G6016"
    - "G840"
    - "G1032"
    - "G1124"

  from_station:
    - "广州"
    - "东莞东"
  to_station:
    - "耒阳"
    - "衡阳"
  set_type:
    - "硬座"
    - "二等座"

  is_more_ticket: Ture
  select_refresh_interval: 0.5
  expect_refresh_interval: 0.5
  ticket_black_list_time: 3

ticke_peoples:
  - "廖书军"

damatu:
  uesr: "elgogle"
  pwd: "car168shut187_"

12306count:
  uesr: "elgogle"
  pwd: "car168shut187_"

